### ISSUE TITLE
Unable access the site

### ISSUE THREAD

**Issue by mazharoddin** [alg/family_hut#1]
Hi, 
thanks for this app, I tried to install this app , installation & setup  was successful and am able to start the server, but am  unable to authenticate the site using user 'first' and password 'first' as mentioned in readme file, please let me know how i can fix this.

**Comment by alg** [comment]
Oh, it's been a while (more than 2 years) I last updated the app. You are right, it haven't created the user record for you. Can you try the following?

```
$ rails console
```

And then, when it shows the prompt:

```
User.create(login: "first", email: "<your>@<email>", password: "first", password_confirmation: "first")
```

Running this should create a user for you. This is just a quick hack to get you going. I'll update seeds file later when I get a moment. Let me know if it helped.

**Comment by mazharoddin** [comment]
Hi, thanks for the quick reply, really appreciate it.
Sorry for the delay, but today i tried and am getting below error while trying to create user as you suggested.
1.9.3-p547 :002 > User.create(login: "first", email: "<my-mail>@gmail.com", password: "first", password_confirmation: "first")
LoadError: cannot load such file -- scrypt
        from /home/mazhar/.rvm/gems/ruby-1.9.3-p547@rails3.1/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
        from /home/mazhar/.rvm/gems/ruby-1.9.3-p547@rails3.1/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in`block in require'
        from /home/mazhar/.rvm/gems/ruby-1.9.3-p547@rails3.1/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /home/mazhar/.rvm/gems/ruby-1.9.3-p547@rails3.1/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in`require'
        from /home/mazhar/.rvm/gems/ruby-1.9.3-p547@rails3.1/gems/authlogic-3.4.2/lib/authlogic/crypto_providers/scrypt.rb:1:in `<top (required)>

# 

1.9.3-p547 :001 > User.all
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
  User Load (2.7ms)  SELECT `users`.\* FROM `users`
 => []

# 

pls let me know how to proceed.
Thanks

**Comment by mazharoddin** [comment]
I could able to resolve above error after adding 'scrypt' gem to Gemfile.

However still am unable to save User details using console.

Am getting below debug info while trying to create new user using rails console.

1.9.3-p547 :002 > User.create(login: "first", email:"<my mail>@gmail.com", password: "first", password_confirmation: "first")
  SQL (0.1ms)  BEGIN
  User Exists (0.3ms)  SELECT 1 FROM `users` WHERE `users`.`email` = '<my mail>@gmail.com' LIMIT 1
  User Exists (0.2ms)  SELECT 1 FROM `users` WHERE `users`.`login` = 'first' LIMIT 1
  User Exists (0.2ms)  SELECT 1 FROM `users` WHERE `users`.`persistence_token` = BINARY '2413c630df8b28f039a62c9be42aeaaebcefbebfa7746b832236419b5c703ca9d2f26322584dd73bf1b066f9625a72c3870bf3f6e8c4fd955b0e2185bf79b535' LIMIT 1
  User Exists (0.2ms)  SELECT 1 FROM `users` WHERE `users`.`single_access_token` = BINARY 'bAI7fdnivjEVySD3nwPH' LIMIT 1
  User Exists (0.4ms)  SELECT 1 FROM `users` WHERE `users`.`login` = BINARY 'first' LIMIT 1
  User Exists (0.2ms)  SELECT 1 FROM `users` WHERE `users`.`email` = BINARY '<my mail>@gmail.com' LIMIT 1
   (0.1ms)  ROLLBACK
 => #<User id: nil, login: "first", name: nil, location: nil, email: "<my mail>@gmail.com", crypted_password: "400$8$a$c309e9e9fcd3d64e$6b6684e44be7c7f502cbbfcf5a...", password_salt: "4O5O4xMer8U8Vt8LZsr4", persistence_token: "2413c630df8b28f039a62c9be42aeaaebcefbebfa7746b83223...", single_access_token: "bAI7fdnivjEVySD3nwPH", perishable_token: nil, login_count: 0, failed_login_count: 0, last_request_at: nil, current_login_at: nil, last_login_at: nil, current_login_ip: nil, last_login_ip: nil, created_at: nil, updated_at: nil, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, locale: "ru", time_zone: "Kyiv">
I believe there is some issue with User model.

**Comment by alg** [comment]
Hi, glad to see you progressed through the “scrypt” issue. You can always ask User mode what’s wrong:

> User.errors.full_messages

Let me know.  
- Aleksey

**Comment by mazharoddin** [comment]
Hi, I could able to resolve issues related to User, there were few password related validations prevented to create user, so I created user by providing password more than 4 characters . however now  i am getting server not found error whenever I try to login ..

log from Developer.log

 Started GET "/" for 192.168.187.1 at 2014-10-01 14:16:55 +0530
 298 Processing by UsersController#dashboard as HTML
 299 Completed 500 Internal Server Error in 10ms
 300
 301 NoMethodError (undefined method `albums' for nil:NilClass):
 302   app/controllers/users_controller.rb:5:in`dashboard'

Rendered users/dashboard.haml within layouts/application (78.3ms)
1083 Completed 500 Internal Server Error in 355ms
1084
1085 ActionView::Template::Error (undefined method `user' for nil:NilClass):
1086     1: .post.box
1087     2:   .avatar= link_to image_tag(post.user.avatar.url(:small)), post.user
1088     3:   = raw post.body
1089     4:   .meta
1090     5:     %span.date=l post.created_at, :format => :long
1091   app/views/users/_post.haml:2:in`_app_views_users__post_haml__332735087779475594_69860731031880'

May be I need to look why method errors are appearing ...
-Mazhar

**Comment by alg** [comment]
I've committed a small fix. Please try and let me know.

**Comment by mazharoddin** [comment]
Thank you,sure I will try and let you know...thanks  a lot ..

**Comment by mazharoddin** [comment]
thanks for the fix, i tried the fix, now am getting different error.
Rendered users/_post.haml (34.6ms)
  Rendered users/dashboard.haml within layouts/application (96.9ms)
Completed 500 Internal Server Error in 378ms

ActionView::Template::Error (undefined method `user' for nil:NilClass):
    1: .post.box  
    2:   .avatar= link_to image_tag(post.user.avatar.url(:small)), post.user
    3:   = raw post.body
    4:   .meta
    5:     %span.date=l post.created_at, :format => :long

may be I need to upload the avatar to fix this issue...

**Comment by alg** [comment]
Are you sure you got the latest updates. It shouldn't be there.

**Comment by mazharoddin** [comment]
oh ok, may be i need to checkout entire repository ...i edit that file manually ...so let me try to re-clone the repository...

**Comment by alg** [comment]
$ git pull

Is all you need.

And you also need to restart the server after any changes to files.

**Comment by mazharoddin** [comment]
yes, I have latest code , but still am getting below error .
 Rendered users/_post.haml (78.1ms)
  Rendered users/dashboard.haml within layouts/application (229.6ms)
Completed 500 Internal Server Error in 556ms

ActionView::Template::Error (undefined method `user' for nil:NilClass):
    1: .post.box
    2:   .avatar= link_to image_tag(post.user.avatar.url(:small)), post.user
    3:   = raw post.body
    4:   .meta
    5:     %span.date=l post.created_at, :format => :long
  app/views/users/_post.haml:2:in`_app_views_users__post_haml___1152280381797406491_39265480'

**Comment by alg** [comment]
Can you paste in here how the app/views/users/dashboard.haml file looks like?

**Comment by mazharoddin** [comment]
sure.... here is the dashboard.haml file content
- @page_title = t(".header")
  2
  3 .row#dashboard
  4   .span10
  5     #photos
  6       %h3= t(".new_photos")
  7       = render @photos
  8
  9   .span6
  10     #posts
  11       %h3= t(".journal")
  12       = render :partial => "users/post_form"
  13       unless @post.nil?
  14       = render :partial => "users/post", :object => @post
  15
  16     #albums
  17       %h3= t(".my_albums")
  18       = link_to t("albums.index.new"), new_album_path
  19
  20       - if @albums.empty?
  21         .no-items= t(".no_albums")
  22       - else
  23         = render :partial => "albums/album", :collection => @albums

**Comment by alg** [comment]
Well, I have no idea why it doesn't work for you. The best is to step through the template and figure why you end up in the app/views/users/_post.haml if post is missing.

**Comment by mazharoddin** [comment]
Sure , I will checkout, thanks a lot for your time and help, really appreciate it
